### ISSUE TITLE
User not being created on nation

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#1838]
When we connect community to nation. User is not being created on nation.

**Comment by paulbert** [comment]
I think this is fixed.  Could you confirm and close if so @lmmrssa ?

**Comment by lmmrssa** [comment]
@paulbert looks like this is still happening sometime. So we need some more test cases to verify.

**Comment by paulbert** [comment]
Closing since this is outdated and likely fixed in #5241

**Comment by paulbert** [comment]
Closing since this is outdated and likely fixed in #5421
